spring:
  application:
    name: media-asset-annotator-server

server:
  port: ${SERVER_PORT:5040}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/annotator-server/api}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSE:health,info}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}

    org.springframework: ${LOG_LEVEL_SPRING:INFO}
    org.springframework.web: ${LOG_LEVEL_WEB:INFO}

    org.springframework.jdbc.core.JdbcTemplate: ${LOG_LEVEL_JDBC:OFF}
    org.springframework.jdbc.core.StatementCreatorUtils: ${LOG_LEVEL_JDBC:OFF}

  pattern:
    console: ${LOG_PATTERN_CONSOLE:%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n}

mediacms:
  internal-base-url: ${MEDIA_CMS_INTERNAL_BASE_URL:http://localhost:2080}
  public-base-url: ${MEDIA_CMS_PUBLIC_BASE_URL:http://localhost:2080}
  api-base: ${MEDIA_CMS_API_BASE:/api/v1}

persistence:
  username: ${DB_USERNAME:admin}
  password: ${DB_PASSWORD:root}
  repository:
    url: ${REPOSITORY_URL:http://localhost:7200/repositories/media-assets}
  driver: cz.cvut.kbss.ontodriver.rdf4j.Rdf4jDataSource


cors:
  enabled: ${CORS_ENABLED:true}
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:2030}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS,PATCH}
  allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
  exposed-headers: ${CORS_EXPOSED_HEADERS:}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
  max-age: ${CORS_MAX_AGE:3600}